uint64 timestamp
uint64 timestamp_sample
uint32 device_id
float32[2] pixel_flow
float32[3] delta_angle
bool delta_angle_available
float32 distance_m
bool distance_available
uint32 integration_timespan_us
uint8 quality
uint32 error_count
float32 max_flow_rate
float32 min_ground_distance
float32 max_ground_distance
uint8 MODE_UNKNOWN = 0
uint8 MODE_BRIGHT = 1
uint8 MODE_LOWLIGHT = 2
uint8 MODE_SUPER_LOWLIGHT = 3
uint8 mode
